#!/bin/bash

binary_name="nc"

script_dir_path=$(dirname $0)
if [ ! -d "$script_dir_path/bin" ]; then
	mkdir $script_dir_path/bin
fi
clang++-11 -std=c++20 -O3 -Wall -o "$script_dir_path/bin/$binary_name" -pthread -fno-exceptions main.cpp NetworkShepherd.cpp
