#!/bin/bash

binary_name="nc"

script_dir_path=$(dirname "$0")
if [ ! -f "$script_dir_path/bin/$binary_name" ]; then
	echo 'ERROR: no binaries to install'
	exit
fi
read -p 'installation directory: ' install_dir
eval install_dir="$install_dir"
if [ ! -d "$install_dir" ]; then
	echo 'ERROR: the provided installation directory does not exist'
	exit
fi
if [ -e "$install_dir/$binary_name" ]; then
	echo 'ERROR: namespace conflict in installation directory, file already exists'
	exit
fi
cp "$script_dir_path/bin/$binary_name" "$install_dir/$binary_name"
